# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aasli <aasli@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/03/05 21:52:28 by aasli             #+#    #+#              #
#    Updated: 2023/03/06 11:22:13 by aasli            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - backend-network
    volumes:
      - database:/var/lib/postgresql/data

  backend:
    build:
      context: api/
    container_name: api
    ports:
      - 3000:3000
      - 5555:3000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network
    volumes:
      - ./api/src/:/app/src
      - ./api/prisma/:/app/prisma

  frontend:
    build:
      context: client/
    container_name: client
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - frontend-network
    volumes:
      - ./client/src:/app/src

networks:
  frontend-network:
  backend-network:

volumes:
  database:


  # admin:
  #   image: adminer
  #   container_name: adminer
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080
